version: '3.9'
services:
  web:
    build:
      context: ../
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"

  database:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    volumes:
    - ../db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    depends_on:
    - web
    networks:
    - default